"""Workspace Language Model with Cayley-Orthogonal Dynamics

Architecture:
  A fixed-size workspace vector z ∈ ℝ^D_WORK evolves through a sequence via
  iterated Euler steps. Each token injects information into z via a gated
  projection, then z is settled by T_SETTLE Euler steps of a token-conditioned
  linear map. The map is a convex combination of N Cayley-orthogonal bases,
  keeping eigenvalues on the unit circle and preventing signal decay across ticks.

Training regime — two simultaneous update rules, never switching:
  Gradient (sensor/motor): embedding, injection gate, classifier head.
    These are trained with standard Adam on cross-entropy loss.
    Brain parameters are stop_gradient'd so gradient does not leak into them.
  Hebbian (brain): Cayley generators (A_gens), scale_proj, bias_proj.
    Updated directly from workspace state correlations, weighted by centered
    prediction quality. No backpropagation touches these parameters.
    The quality signal is cosine similarity between the post-settle workspace
    readout and the target token embedding — weak at initialization, strengthens
    as the sensor learns to produce useful embeddings.

Cayley / skew-symmetric basis:
  Each of the N basis matrices is generated by exp(-A)(exp(A))^T = (I+A)^{-1}(I-A)
  for a skew-symmetric A (A = -A^T). This is the Cayley map. All eigenvalues of the
  resulting orthogonal matrix lie on the unit circle, so iterative application
  neither contracts nor explodes workspace state.
  After each Hebbian update, A_gens are re-projected to skew-symmetry by
  A ← (A - A^T) / 2, maintaining the invariant.

Selector (mixture of bases):
  alpha = softmax(emb @ selector)  — token embedding picks a convex blend of
  the N orthogonal bases. This is a soft routing without a learned gate network;
  the selector matrix IS the router.
"""

import sys, os, time
os.environ["PYTHONUNBUFFERED"] = "1"
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
import jax
import jax.numpy as jnp
import equinox as eqx
import optax
import wandb

from transformers import AutoTokenizer

# --- Hyperparameters ---
D_WORK = 1024       # workspace dimension (the single recurrent vector)
D_EMB = 256         # token embedding dimension
N_BASIS = 16        # number of Cayley basis matrices in the mixture
T_SETTLE = 5        # Euler settle steps per token
DT = 0.1            # Euler step size
MAX_LEN = 200       # maximum sequence length
BATCH_SIZE = 16
MAX_STEPS = 30000
LR_GRAD = 3e-4
LR_HEBB = 0.0005    # conservative — Hebbian signal is cosine similarity, noisy early


def rms_norm(s):
    """RMS normalization. Keeps workspace magnitude stable across settle steps."""
    return s / (jnp.sqrt(jnp.mean(s ** 2)) + 1e-5)

def cayley(A_skew):
    """Cayley map: skew-symmetric A → orthogonal matrix with all eigenvalues on unit circle.
    Uses the identity (I + A)^{-1}(I - A) = (I - A)(I + A)^{-1} for skew A.
    Implemented as a linear solve to avoid explicit matrix inverse.
    """
    I = jnp.eye(A_skew.shape[0])
    return jnp.linalg.solve(I + A_skew, I - A_skew)


class SimultaneousLM(eqx.Module):
    # Sensor/motor parameters — trained by gradient
    embedding: jnp.ndarray       # (vocab_size, d_emb)
    pos_embedding: jnp.ndarray   # (max_len, d_emb) — learned absolute positions
    inject_proj: jnp.ndarray     # (d_emb, D_work) — linear projection of token into workspace space
    inject_gate_w: jnp.ndarray   # (D_work + d_emb, D_work) — gate input: concat(z, emb)
    inject_gate_b: jnp.ndarray   # (D_work,)
    cls_w: jnp.ndarray           # (D_work, d_emb) — read workspace into embedding space
    cls_b: jnp.ndarray           # (d_emb,)
    # Brain parameters — trained by Hebbian rule only
    A_gens: jnp.ndarray          # (N, D_work, D_work) — skew-symmetric generators; Cayley(A_gens[i]) = basis i
    selector: jnp.ndarray        # (d_emb, N) — token embedding → mixture weights over bases
    scale_proj: jnp.ndarray      # (d_emb, D_work) — token-conditioned element-wise gain
    scale_base: jnp.ndarray      # (D_work,) — base gain (initialized to 1)
    bias_proj: jnp.ndarray       # (d_emb, D_work) — token-conditioned additive bias
    bias_base: jnp.ndarray       # (D_work,) — base bias (initialized to 0)
    D_work: int = eqx.field(static=True)
    d_emb: int = eqx.field(static=True)
    vocab_size: int = eqx.field(static=True)
    N: int = eqx.field(static=True)

    def __init__(self, vocab_size, d_emb, D_work, N, max_len=200, *, key):
        keys = jax.random.split(key, 12)
        self.vocab_size, self.d_emb, self.D_work, self.N = vocab_size, d_emb, D_work, N

        self.embedding = jax.random.normal(keys[0], (vocab_size, d_emb)) * 0.02
        self.pos_embedding = jax.random.normal(keys[1], (max_len, d_emb)) * 0.01
        # He-style init for projection matrices
        self.inject_proj = jax.random.normal(keys[2], (d_emb, D_work)) * (2.0 / d_emb) ** 0.5
        self.inject_gate_w = jax.random.normal(keys[3], (D_work + d_emb, D_work)) * (2.0 / (D_work + d_emb)) ** 0.5
        self.inject_gate_b = jnp.zeros(D_work)
        self.cls_w = jax.random.normal(keys[4], (D_work, d_emb)) * (2.0 / D_work) ** 0.5
        self.cls_b = jnp.zeros(d_emb)

        # Initialize A_gens small so Cayley(A) ≈ I at the start
        raw = jax.random.normal(keys[5], (N, D_work, D_work)) * (0.3 / jnp.sqrt(jnp.float32(D_work)))
        self.A_gens = (raw - jnp.swapaxes(raw, -2, -1)) / 2.0  # enforce skew-symmetry at init
        self.selector = jax.random.normal(keys[6], (d_emb, N)) * (1.0 / jnp.sqrt(jnp.float32(d_emb)))
        self.scale_proj = jax.random.normal(keys[7], (d_emb, D_work)) * (0.1 / jnp.sqrt(jnp.float32(d_emb)))
        self.scale_base = jnp.ones(D_work)
        self.bias_proj = jax.random.normal(keys[8], (d_emb, D_work)) * (0.1 / jnp.sqrt(jnp.float32(d_emb)))
        self.bias_base = jnp.zeros(D_work)


def inject_token(model, z, emb):
    """Gated injection of token embedding into workspace.
    Gate is conditioned on both the current workspace state and the token embedding,
    so the model can suppress injection when the workspace is already relevant.
    z ← z * (1 - gate) + proj(emb) * gate
    """
    proj = emb @ model.inject_proj
    gate = jax.nn.sigmoid(jnp.concatenate([z, emb]) @ model.inject_gate_w + model.inject_gate_b)
    return z * (1 - gate) + proj * gate

def classify(model, z):
    """Read workspace into embedding space, L2-normalize, then dot against normalized vocab embeddings.
    Scaled dot product (×30) sharpens the distribution before softmax — equivalent to a temperature.
    Cosine similarity over embeddings makes the classifier invariant to embedding norm.
    """
    h = z @ model.cls_w + model.cls_b
    h = h / (jnp.linalg.norm(h) + 1e-8)
    emb_n = model.embedding / (jnp.linalg.norm(model.embedding, axis=1, keepdims=True) + 1e-8)
    return (h @ emb_n.T) * 30.0


def forward_sequence_dual(model, token_ids, T, dt):
    """Autoregressive forward pass for gradient training.

    Brain parameters (A_gens, selector, scale_proj, scale_base, bias_proj, bias_base)
    are stop_gradient'd here. Gradient flows only through sensor/motor parameters:
    embedding, pos_embedding, inject_proj, inject_gate_*, cls_w, cls_b.

    This is not a hack — it enforces the architectural boundary: the brain learns
    by correlation (Hebbian), not by error backpropagation. stop_gradient makes the
    brain parameters a fixed dynamical system from gradient's perspective.

    Returns logits for positions 0..L-2 (predicting tokens 1..L-1).
    """
    L = token_ids.shape[0]
    embeds = model.embedding[token_ids] + model.pos_embedding[:L]

    # Detach brain params from the gradient graph
    A_gens_sg = jax.lax.stop_gradient(model.A_gens)
    selector_sg = jax.lax.stop_gradient(model.selector)
    scale_proj_sg = jax.lax.stop_gradient(model.scale_proj)
    scale_base_sg = jax.lax.stop_gradient(model.scale_base)
    bias_proj_sg = jax.lax.stop_gradient(model.bias_proj)
    bias_base_sg = jax.lax.stop_gradient(model.bias_base)

    # Compute all N orthogonal bases once per sequence (not per token)
    bases = jax.vmap(cayley)(A_gens_sg)
    z = jnp.zeros(model.D_work)

    def process_token(z, t):
        emb = embeds[t]
        # Token selects a soft mixture of orthogonal bases
        alpha = jax.nn.softmax(emb @ selector_sg)
        W = jnp.einsum('n,nij->ij', alpha, bases)
        # Token-conditioned scale and bias modulate the dynamics
        scale = jax.nn.softplus(emb @ scale_proj_sg + scale_base_sg) + 0.5
        bias = emb @ bias_proj_sg + bias_base_sg

        z = inject_token(model, z, emb)
        # Euler settle: z ← rms_norm(z + dt * (scale * W @ gelu(z) + bias))
        def settle(z, _):
            response = scale * (W @ jax.nn.gelu(z)) + bias
            return rms_norm(z + dt * response), None
        z, _ = jax.lax.scan(settle, z, None, length=T)
        logits = classify(model, z)
        return z, logits

    _, all_logits = jax.lax.scan(process_token, z, jnp.arange(L - 1))
    return all_logits


def loss_fn(model, batch_ids, T, dt):
    """Mean per-token cross-entropy over a batch, masked on padding (token id 0)."""
    def single(token_ids):
        logits = forward_sequence_dual(model, token_ids, T, dt)
        targets = token_ids[1:]
        log_probs = jax.nn.log_softmax(logits, axis=-1)
        ce = -log_probs[jnp.arange(targets.shape[0]), targets]
        mask = targets != 0
        return jnp.sum(ce * mask) / (jnp.sum(mask) + 1e-8)
    return jnp.mean(jax.vmap(single)(batch_ids))


def hebbian_update(model, batch_ids, T, dt):
    """Hebbian update for brain parameters, driven by prediction quality.

    Update rule (for each parameter P):
      ΔP ∝ Σ_t  q_t * outer(post_activity, pre_activity)
    where q_t = quality_t - mean_quality is the centered quality signal.
    Centering (baseline subtraction) is critical: it makes positive-quality steps
    reinforce the active pathway and negative-quality steps suppress it.

    Quality signal: cosine similarity between the workspace readout (cls projection)
    and the target token embedding. Range [-1, 1]. Noisy early in training when
    embeddings are random; becomes meaningful as sensor training progresses.

    Cayley generator update:
      dA_i ∝ skew(Σ_t  q_t * alpha_i(t) * post_t ⊗ gelu(pre_t))
    The skew projection dA = (dH - dH^T)/2 ensures the generator stays
    skew-symmetric, so Cayley(A_i) remains orthogonal.
    Generator norms are clipped to 3√D to prevent divergence.

    Scale and bias projections use the same quality-weighted correlation rule
    without the skew projection, since they are not constrained to orthogonality.
    """
    L = batch_ids.shape[1]

    def collect_states(token_ids):
        embeds = model.embedding[token_ids] + model.pos_embedding[:L]
        bases = jax.vmap(cayley)(model.A_gens)
        z = jnp.zeros(model.D_work)

        def process(z, t):
            emb = embeds[t]
            alpha = jax.nn.softmax(emb @ model.selector)
            W = jnp.einsum('n,nij->ij', alpha, bases)
            scale = jax.nn.softplus(emb @ model.scale_proj + model.scale_base) + 0.5
            bias = emb @ model.bias_proj + model.bias_base

            z_pre = z   # workspace state before injection + settle
            z = inject_token(model, z, emb)
            def settle(z, _):
                return rms_norm(z + dt * (scale * (W @ jax.nn.gelu(z)) + bias)), None
            z, _ = jax.lax.scan(settle, z, None, length=T)

            # Cosine similarity between readout and target embedding as the quality signal
            pred = z @ model.cls_w + model.cls_b
            pred = pred / (jnp.linalg.norm(pred) + 1e-8)
            target_id = token_ids[jnp.minimum(t + 1, L - 1)]
            target = model.embedding[target_id]
            target = target / (jnp.linalg.norm(target) + 1e-8)
            quality = jnp.dot(pred, target)

            return z, (z_pre, z, quality, alpha, emb)

        _, (pres, posts, quals, alphas, embs) = jax.lax.scan(process, z, jnp.arange(L - 1))
        return pres, posts, quals, alphas, embs

    all_pre, all_post, all_qual, all_alpha, all_embs = jax.vmap(collect_states)(batch_ids)

    # Flatten batch and sequence dimensions into a single sample axis
    flat_pre = all_pre.reshape(-1, model.D_work)
    flat_post = all_post.reshape(-1, model.D_work)
    flat_qual = all_qual.reshape(-1)
    flat_alpha = all_alpha.reshape(-1, model.N)
    flat_embs = all_embs.reshape(-1, model.d_emb)
    M = flat_pre.shape[0]

    mean_quality = jnp.mean(flat_qual)
    q = flat_qual - mean_quality  # centered quality (baseline subtraction)

    # Update Cayley generators: skew-projected quality-weighted outer product
    def update_gen(i, A_gens):
        w = q * flat_alpha[:, i]   # quality weighted by this basis's mixture weight
        dH = jnp.einsum('m,mi,mj->ij', w, flat_post, jax.nn.gelu(flat_pre)) / M
        dA = (dH - dH.T) / 2.0    # skew projection — keeps A_gens skew-symmetric
        new_A = A_gens[i] + LR_HEBB * dA
        # Clip Frobenius norm to prevent generator explosion
        An = jnp.linalg.norm(new_A, ord='fro')
        mx = 3.0 * jnp.sqrt(jnp.float32(model.D_work))
        new_A = jnp.where(An > mx, new_A * mx / (An + 1e-8), new_A)
        return A_gens.at[i].set(new_A)

    new_A = jax.lax.fori_loop(0, model.N, update_gen, model.A_gens)

    # Update scale projection: quality-weighted (emb, |post|) correlation
    d_sp = jnp.einsum('m,mi,mj->ij', q, flat_embs, jnp.abs(flat_post)) / M
    new_sp = model.scale_proj + LR_HEBB * d_sp

    # Update bias projection: quality-weighted (emb, post) correlation
    d_bp = jnp.einsum('m,mi,mj->ij', q, flat_embs, flat_post) / M
    new_bp = model.bias_proj + LR_HEBB * d_bp

    model = eqx.tree_at(lambda m: m.A_gens, model, new_A)
    model = eqx.tree_at(lambda m: m.scale_proj, model, new_sp)
    model = eqx.tree_at(lambda m: m.bias_proj, model, new_bp)
    return model, mean_quality


@eqx.filter_jit
def train_step(model, opt_state, batch_ids, T, dt, optimizer):
    """Gradient step on sensor/motor parameters only.

    Brain parameters are already stop_gradient'd inside forward_sequence_dual,
    so their gradient entries are structurally zero. The explicit zeroing below
    is defensive — it ensures no residual gradient reaches the optimizer for
    brain params via any other code path.
    """
    loss, grads = eqx.filter_value_and_grad(loss_fn)(model, batch_ids, T, dt)

    # Zero brain parameter gradients explicitly as a defensive measure
    zero = jnp.zeros_like
    grads = eqx.tree_at(lambda m: m.A_gens, grads, zero(model.A_gens))
    grads = eqx.tree_at(lambda m: m.selector, grads, zero(model.selector))
    grads = eqx.tree_at(lambda m: m.scale_proj, grads, zero(model.scale_proj))
    grads = eqx.tree_at(lambda m: m.scale_base, grads, zero(model.scale_base))
    grads = eqx.tree_at(lambda m: m.bias_proj, grads, zero(model.bias_proj))
    grads = eqx.tree_at(lambda m: m.bias_base, grads, zero(model.bias_base))

    updates, opt_state = optimizer.update(grads, opt_state, model)
    model = eqx.apply_updates(model, updates)
    return model, opt_state, loss


@eqx.filter_jit
def hebbian_step_jit(model, batch_ids, T, dt):
    return hebbian_update(model, batch_ids, T, dt)


def generate(model, tokenizer, prompt, max_new=50, T=5, dt=0.1, temperature=0.8, top_k=40):
    """Autoregressive generation. Workspace state is carried across tokens (no reset).
    Prompt tokens prime the workspace, then new tokens are sampled one at a time.
    top_k=0 disables top-k filtering (full vocabulary sampling).
    """
    token_ids = tokenizer(prompt, return_tensors="np")["input_ids"][0].astype(np.int32)
    bases = jax.vmap(cayley)(model.A_gens)
    z = jnp.zeros(model.D_work)
    generated = list(token_ids)
    L = model.pos_embedding.shape[0]

    # Process prompt — prime the workspace
    for i in range(len(token_ids)):
        pos = min(i, L - 1)
        emb = model.embedding[token_ids[i]] + model.pos_embedding[pos]
        alpha = jax.nn.softmax(emb @ model.selector)
        W = jnp.einsum('n,nij->ij', alpha, bases)
        scale = jax.nn.softplus(emb @ model.scale_proj + model.scale_base) + 0.5
        bias = emb @ model.bias_proj + model.bias_base
        z = inject_token(model, z, emb)
        for _ in range(T):
            z = rms_norm(z + dt * (scale * (W @ jax.nn.gelu(z)) + bias))

    rng = jax.random.PRNGKey(42)
    for i in range(max_new):
        logits = classify(model, z) / temperature
        if top_k > 0:
            tv, ti = jax.lax.top_k(logits, top_k)
            logits = jnp.full_like(logits, -1e9).at[ti].set(tv)
        rng, sk = jax.random.split(rng)
        nid = int(jax.random.categorical(sk, logits))
        generated.append(nid)
        pos = min(len(token_ids) + i, L - 1)
        emb = model.embedding[nid] + model.pos_embedding[pos]
        alpha = jax.nn.softmax(emb @ model.selector)
        W = jnp.einsum('n,nij->ij', alpha, bases)
        scale = jax.nn.softplus(emb @ model.scale_proj + model.scale_base) + 0.5
        bias = emb @ model.bias_proj + model.bias_base
        z = inject_token(model, z, emb)
        for _ in range(T):
            z = rms_norm(z + dt * (scale * (W @ jax.nn.gelu(z)) + bias))

    return tokenizer.decode(generated)


def main():
    tokenizer = AutoTokenizer.from_pretrained("bigcode/starcoder2-3b", trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    print("Loading wiki data...")
    all_ids = np.load("precomputed_targets/wiki_long_512.npy")[:, :MAX_LEN]
    N_data = all_ids.shape[0]

    key = jax.random.PRNGKey(42)
    model = SimultaneousLM(vocab_size=tokenizer.vocab_size, d_emb=D_EMB,
                            D_work=D_WORK, N=N_BASIS, max_len=MAX_LEN, key=key)

    total_params = sum(x.size for x in jax.tree.leaves(eqx.filter(model, eqx.is_array)))
    print(f"  Params: {total_params:,}")

    optimizer = optax.chain(optax.clip_by_global_norm(1.0), optax.adam(LR_GRAD))
    opt_state = optimizer.init(eqx.filter(model, eqx.is_array))

    wandb.init(project="iPC-Chain", name="workspace-lm-cayley-hebbian", config={
        "D_work": D_WORK, "N_basis": N_BASIS, "T": T_SETTLE,
        "lr_grad": LR_GRAD, "lr_hebb": LR_HEBB,
        "total_params": total_params,
    })

    print(f"\n{'='*60}")
    print(f"Workspace LM: simultaneous gradient (sensor) + Hebbian (brain)")
    print(f"  Gradient: embedding, injection, classifier")
    print(f"  Hebbian:  Cayley generators, scale, bias")
    print(f"  LR grad={LR_GRAD}, LR hebb={LR_HEBB}")
    print(f"{'='*60}")

    indices = np.arange(N_data)
    t0 = time.time()

    for step in range(1, MAX_STEPS + 1):
        batch_idx = np.random.choice(indices, BATCH_SIZE, replace=False)
        b_ids = jnp.array(all_ids[batch_idx])

        # Gradient step (sensor/motor): embedding, injection gate, classifier
        model, opt_state, loss = train_step(model, opt_state, b_ids, T_SETTLE, DT, optimizer)

        # Hebbian step (brain): Cayley generators, scale, bias — same batch
        model, quality = hebbian_step_jit(model, b_ids, T_SETTLE, DT)

        # Re-project A_gens to skew-symmetry after Hebbian update.
        # Numerical drift during the update can introduce symmetric components;
        # this one-liner removes them and ensures Cayley(A_gens[i]) stays orthogonal.
        new_A = (model.A_gens - jnp.swapaxes(model.A_gens, -2, -1)) / 2.0
        model = eqx.tree_at(lambda m: m.A_gens, model, new_A)

        if step % 250 == 0:
            ppl = float(jnp.exp(jnp.minimum(loss, 10.0)))
            elapsed = time.time() - t0
            wandb.log({
                'train/loss': float(loss), 'train/ppl': ppl,
                'train/quality': float(quality),
            }, step=step)
            print(f"  [{step:>5d}] loss={float(loss):.3f} ppl={ppl:.1f} "
                  f"q={float(quality):.4f} ({step/elapsed:.1f} s/s)")

        if step % 5000 == 0:
            for p in ["The history of", "Scientists discovered"]:
                try:
                    s = generate(model, tokenizer, p, max_new=40, T=T_SETTLE, dt=DT)
                    print(f"    Gen: {s[:120]}...")
                except Exception as e:
                    print(f"    Gen err: {e}")

    final_ppl = float(jnp.exp(jnp.minimum(loss, 10.0)))
    print(f"\n{'='*60}")
    print(f"Final result")
    print(f"  Final PPL:     {final_ppl:.1f}")
    print(f"  Final quality: {float(quality):.4f}")
    print(f"{'='*60}")

    for p in ["The history of", "In mathematics,", "Scientists discovered"]:
        try:
            s = generate(model, tokenizer, p, max_new=50, T=T_SETTLE, dt=DT)
            print(f"  {s[:140]}...")
        except:
            pass

    wandb.log({'final_ppl': final_ppl})
    wandb.finish()


if __name__ == "__main__":
    main()
